# Generated by Django 4.2 on 2024-05-16 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_service', '0002_customuser_password1_customuser_password2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
    ]
